name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Triggers on push to main branch
  pull_request:
    branches: [ main ]  # Optional: also trigger on PRs to main
  workflow_dispatch:    # Allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/your-image:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cache:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/cache:buildcache,mode=max
