name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Convert GitHub username to lowercase
      - name: Prepare repository name
        id: prep
        run: |
          echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=your-image" >> $GITHUB_OUTPUT
          echo "CACHE_NAME=cache" >> $GITHUB_OUTPUT
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.prep.outputs.REPO_OWNER }}/${{ steps.prep.outputs.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=ghcr.io/${{ steps.prep.outputs.REPO_OWNER }}/${{ steps.prep.outputs.CACHE_NAME }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.prep.outputs.REPO_OWNER }}/${{ steps.prep.outputs.CACHE_NAME }}:buildcache,mode=max
